% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Prueba de Hipótesis},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\newenvironment{Shaded}{}{}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{1.00,0.00,0.00}{\textbf{#1}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.38,0.63,0.69}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.49,0.56,0.16}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.25,0.63,0.44}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.25,0.44,0.63}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.38,0.63,0.69}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.38,0.63,0.69}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.53,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.56,0.13,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.25,0.63,0.44}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.73,0.13,0.13}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{1.00,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.25,0.63,0.44}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.02,0.16,0.49}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.38,0.63,0.69}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.40,0.40,0.40}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.74,0.48,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.25,0.44,0.63}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.73,0.40,0.53}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.25,0.44,0.63}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.10,0.09,0.49}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.25,0.44,0.63}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.38,0.63,0.69}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Prueba de Hipótesis}
\author{}
\date{\vspace{-2.5em}5/3/2021}

\begin{document}
\maketitle

\hypertarget{prueba-de-hipuxf3tesis}{%
\subsection{Prueba de Hipótesis}\label{prueba-de-hipuxf3tesis}}

El método científico es un proceso con el cual se investiga de forma
sistemática las observaciones, se resuelven problemas y se prueban
hipótesis. Como parte del método científico la propuesta de una
hipótesis y luego su comprobación, son temas bien definidos, y a pesar
de la incertidumbre asociada al problema es posible cuantificar el error
de la conclusión planteada por la hipótesis.

Los pasos del método científico son: Plantear un problema a resolver,
Colectar una serie de observaciones, formular una o más hipótesis,
probar dichas hipótesis y declarar las conclusiones. Aqui exploraremos
herramientas estadísticas que nos puede ayudar el paso de prueba de
hipótesis. Una hipótesis se puede definir de la siguiente manera: Una
explicación tentativa que cuenta con un conjunto de hechos que pueden
ser probados con una investigación posterior.

A su vez los pasos para poder efectuar una prueba de hipótesis son los
siguientes:

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\item
  Establecer las hipótesis en base a lo que se pretende verificar. Fijar
  \(H_0\) y \(H_1\)
\item
  Definir la prueba adecuada. Buscar el estadístico del test que bajo la
  hipótesis nula tenga una distribución conocida
\item
  Definir el nivel de riesgo o precisión que lleva a determinar la
  región crítica
\item
  Seleccionar una muestra de tamaño 𝑛, para la cual el estadístico de
  contraste tome un valor numérico (valor experimental del estadístico
  de contraste
\item
  Adoptar la decisión sobre el rechazo o no de \(H_0\)
\end{enumerate}

Como en el práctico de estimación las veremos como realizar contraste de
hipótesis a traves de pruebas para los siguientes estadísticos:

\begin{itemize}
\tightlist
\item
  media \(\mu\),
\item
  proporción \(p\),
\item
  varianza \(\sigma^2\),
\item
  diferencia de medias \(\mu_1-\mu_2\) para muestras independientes y
  dependientes (o pareadas),
\item
  diferencia de proporciones \(p_1 - p_2\), y
\item
  cociente de varianzas \(\sigma_1^2 / \sigma_2^2\).
\end{itemize}

\hypertarget{prueba-de-hipuxf3tesis-para-mu-con-muestras-grandes}{%
\subsubsection{\texorpdfstring{Prueba de hipótesis para \(\mu\) con
muestras
grandes}{Prueba de hipótesis para \textbackslash mu con muestras grandes}}\label{prueba-de-hipuxf3tesis-para-mu-con-muestras-grandes}}

\hypertarget{ejemplo-autos}{%
\paragraph{Ejemplo autos}\label{ejemplo-autos}}

Se afirma que los autos particulares recorren en promedio más de 20000
kilómetros por año pero hay quienes dicen que este promedio es en
realidad menor. Para probar esta afirmación se pide a una muestra de 100
propietarios de autos seleccionada de manera aleatoria que lleven un
registro de los kilómetros que recorren en un año.

De la muestra se obtienen los siguientes datos:

Media = 19500 DE = 3900

En este problema un planteo podría ser:

\[H_0: \mu \ge 20000 \quad km\] \[H_1: \mu < 20000 \quad km\]

Vamos a hacer paso a paso los cálculos para obtener los resultados
deseados, a continuación las instrucciones para calcular el estadístico
y su valor-p.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}

\NormalTok{xbarra }\OtherTok{\textless{}{-}} \DecValTok{19500}  \CommentTok{\# Datos del problema}
\NormalTok{desvio }\OtherTok{\textless{}{-}} \DecValTok{3900}   \CommentTok{\# Datos del problema}
\NormalTok{n }\OtherTok{\textless{}{-}} \DecValTok{100}         \CommentTok{\# Datos del problema}
\NormalTok{mu }\OtherTok{\textless{}{-}} \DecValTok{20000}      \CommentTok{\# Media de referencia}
\NormalTok{est }\OtherTok{\textless{}{-}}\NormalTok{ (xbarra }\SpecialCharTok{{-}}\NormalTok{ mu) }\SpecialCharTok{/}\NormalTok{ (desvio }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(n))}
\NormalTok{est  }\CommentTok{\# Para obtener el valor del estadístico}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.282051
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xvals }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\FloatTok{0.1}\NormalTok{)}\CommentTok{\# 120:200}

\NormalTok{plotdata }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =}\NormalTok{ xvals, }\AttributeTok{y =} \FunctionTok{dnorm}\NormalTok{(xvals, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{))}

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =} \FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\FloatTok{0.1}\NormalTok{)), }\FunctionTok{aes}\NormalTok{(x))}\SpecialCharTok{+}
 
  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{args =}\FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \DecValTok{1}\NormalTok{),}
                \AttributeTok{geom =} \StringTok{"area"}\NormalTok{,}\AttributeTok{fill=}\StringTok{"blue2"}\NormalTok{,}\AttributeTok{alpha=}\FloatTok{0.5}\NormalTok{)}\SpecialCharTok{+}

  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \DecValTok{1}\NormalTok{), }\AttributeTok{xlim =} \FunctionTok{c}\NormalTok{(}\FloatTok{1.64}\NormalTok{, }\DecValTok{4}\NormalTok{),}
                \AttributeTok{geom =}\StringTok{"area"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"red"}\NormalTok{,}\AttributeTok{alpha=}\FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hiptest_files/figure-latex/unnamed-chunk-1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pnorm}\NormalTok{(est)  }\CommentTok{\# Para obtener el valor{-}P}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.09991233
\end{verbatim}

Como el valor-P es mayor que el nivel de significancia 5\%, no hay
evidencias suficientes para pensar que es menor el recorrido anual
promedio de los autos.

\hypertarget{prueba-de-hipuxf3tesis-para-mu}{%
\subsubsection{\texorpdfstring{Prueba de hipótesis para
\(\mu\)}{Prueba de hipótesis para \textbackslash mu}}\label{prueba-de-hipuxf3tesis-para-mu}}

\hypertarget{ejemplo-cafe}{%
\paragraph{Ejemplo Cafe}\label{ejemplo-cafe}}

Para verificar si el proceso de llenado de bolsas de café con 500 gramos
está operando correctamente se toman aleatoriamente muestras de tamaño
diez cada cuatro horas. Una muestra de bolsas está compuesta por las
siguientes observaciones: 502, 501, 497, 491, 496, 501, 502, 500, 489,
490.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{contenido }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{510}\NormalTok{, }\DecValTok{492}\NormalTok{, }\DecValTok{494}\NormalTok{, }\DecValTok{498}\NormalTok{, }\DecValTok{492}\NormalTok{,}
               \DecValTok{496}\NormalTok{, }\DecValTok{502}\NormalTok{, }\DecValTok{491}\NormalTok{, }\DecValTok{507}\NormalTok{, }\DecValTok{496}\NormalTok{))}
\FunctionTok{colnames}\NormalTok{(contenido) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"gramos"}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(contenido, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{sample=}\NormalTok{gramos)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_qq}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{geom\_qq\_line}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{\textquotesingle{}Cuantiles teóricos\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{\textquotesingle{}Cuantiles muestrales\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hiptest_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(contenido}\SpecialCharTok{$}\NormalTok{gramos)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 497.8
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sd}\NormalTok{(contenido}\SpecialCharTok{$}\NormalTok{gramos)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.545567
\end{verbatim}

¿Está el proceso llenando bolsas conforme lo dice la envoltura? Use un
nivel de significancia del 5\%.

El planteo de hipótesis se puede resumir así:

\[H_0: \mu = 500 \quad gr\] \[H_1: \mu \neq 500 \quad gr\]

La prueba de hipótesis se puede realizar usando la función
\texttt{t.test} por medio del siguiente código.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(contenido, }\AttributeTok{alternative=}\StringTok{\textquotesingle{}two.sided\textquotesingle{}}\NormalTok{,}
       \AttributeTok{conf.level=}\FloatTok{0.95}\NormalTok{, }\AttributeTok{mu=}\DecValTok{500}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  contenido
## t = -1.0629, df = 9, p-value = 0.3155
## alternative hypothesis: true mean is not equal to 500
## 95 percent confidence interval:
##  493.1176 502.4824
## sample estimates:
## mean of x 
##     497.8
\end{verbatim}

Como el valor-P es 30\% y mayor que el nivel de significancia 5\%, no se
rechaza la hipótesis nula, es decir, las evidencias no son suficientes
para afirmar que el proceso de llenando no está cumpliendo con lo
impreso en la envoltura.

\hypertarget{prueba-de-hipuxf3tesis-para-la-proporciuxf3n-p}{%
\subsubsection{\texorpdfstring{Prueba de hipótesis para la proporción
\(p\)}{Prueba de hipótesis para la proporción p}}\label{prueba-de-hipuxf3tesis-para-la-proporciuxf3n-p}}

\hypertarget{ejemplo-quitamanchas}{%
\paragraph{Ejemplo quitamanchas}\label{ejemplo-quitamanchas}}

Existen varias pruebas para estudiar la propoción \(p\) de una
distribución binomial, a continuación el listado de las más comunes.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Prueba de \href{https://en.wikipedia.org/wiki/Wald_test}{Wald},
\item
  Prueba \(X^2\) de
  \href{https://en.wikipedia.org/wiki/Pearson\%27s_chi-squared_test\#Fairness_of_dice}{Pearson},
\item
  Prueba \href{https://en.wikipedia.org/wiki/Binomial_test}{binomial
  exacta}.
\end{enumerate}

\hypertarget{prueba-de-wald}{%
\subparagraph{Prueba de Wald}\label{prueba-de-wald}}

Esta prueba se recomienda usar cuando se tiene un tamaño de muestra
\(n\) suficientemente grande para poder usar la distribución normal para
aproximar la distribución binomial.

En esta prueba el estadístico está dado por

\[z=\frac{\hat{p}-p_0}{\sqrt{\frac{p_0(1-p_0)}{n}}},\] donde \(\hat{p}\)
es la proporción muestral calculada como el cociente entre el número de
éxitos \(x\) observados en los \(n\) ensayos y \(p_0\) es el valor de
referencia de las hipótesis. El estadístico \(z\) tiene distribución
\(N(0, 1)\) cuando \(n \to \infty\).

Un fabricante de un quitamanchas afirma que su producto quita 90\% de
todas las manchas. Para poner a prueba esta afirmación se toman 200
camisetas manchadas de las cuales a solo 174 les desapareció la mancha.
Pruebe la afirmación del fabricante a un nivel \(\alpha=0.05\).

En este problema interesa probar lo siguiente:

\[H_0: p = 0.90\] \[H_1: p < 0.90\]

Del anterior conjunto de hipótesis se observa que el valor de referencia
de la prueba es \(p_0=0.90\). De la información inicial se tiene que de
las \(n=200\) pruebas se observó que en \(x=174\) la mancha desapareció,
con esta información se puede calcular el estadístico \(z\) así:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z }\OtherTok{\textless{}{-}}\NormalTok{ (}\DecValTok{174}\SpecialCharTok{/}\DecValTok{200} \SpecialCharTok{{-}} \FloatTok{0.90}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\FloatTok{0.90} \SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}} \FloatTok{0.90}\NormalTok{) }\SpecialCharTok{/} \DecValTok{200}\NormalTok{)}
\NormalTok{z  }\CommentTok{\# Para obtener el valor del estadístico}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.414214
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =} \FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\FloatTok{0.1}\NormalTok{)), }\FunctionTok{aes}\NormalTok{(x))}\SpecialCharTok{+}
 
  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{args =}\FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \DecValTok{1}\NormalTok{),}
                \AttributeTok{geom =} \StringTok{"area"}\NormalTok{,}\AttributeTok{fill=}\StringTok{"blue2"}\NormalTok{,}\AttributeTok{alpha=}\FloatTok{0.5}\NormalTok{)}\SpecialCharTok{+}

  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \DecValTok{1}\NormalTok{), }\AttributeTok{xlim =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{1.64}\NormalTok{, }\SpecialCharTok{{-}}\DecValTok{4}\NormalTok{),}
                \AttributeTok{geom =}\StringTok{"area"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"red"}\NormalTok{,}\AttributeTok{alpha=}\FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hiptest_files/figure-latex/unnamed-chunk-4-1.pdf}

Para obtener el valor-P de la prueba debemos tener en cuenta el sentido
en la hipótesis alternativa \(H_1: p < 0.90\), por esa razón el valor-P
será \(P(Z<z)\) y para obtenerlo usamos el siguiente código

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pnorm}\NormalTok{(}\AttributeTok{q=}\NormalTok{z, }\AttributeTok{lower.tail=}\ConstantTok{TRUE}\NormalTok{)  }\CommentTok{\# Para obtener el valor{-}P}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0786496
\end{verbatim}

\hypertarget{prueba-x2-de-pearson}{%
\subparagraph{\texorpdfstring{Prueba \(X^2\) de
Pearson}{Prueba X\^{}2 de Pearson}}\label{prueba-x2-de-pearson}}

Para realizar la prueba \(X^2\) de Pearson se usa la función
\texttt{prop.test}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{300}\NormalTok{)), }\FunctionTok{aes}\NormalTok{(x))}\SpecialCharTok{+}
 
  \FunctionTok{stat\_function}\NormalTok{(}\AttributeTok{fun =}\NormalTok{ dchisq, }\AttributeTok{args =}\FunctionTok{list}\NormalTok{(}\AttributeTok{df=}\DecValTok{199}\NormalTok{),}
                \AttributeTok{geom =} \StringTok{"area"}\NormalTok{,}\AttributeTok{fill=}\StringTok{"blue2"}\NormalTok{,}\AttributeTok{alpha=}\FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Los argumentos a definir dentro de \texttt{prop.test} para hacer la
prueba son:

\begin{itemize}
\tightlist
\item
  \texttt{x}: número de éxitos en la muestra.
\item
  \texttt{n}: número de observaciones en la muestra.
\item
  \texttt{alternative}: tipo de hipótesis alterna. Los valores
  disponibles son \texttt{"two.sided"} cuando la alterna es \(\neq\),
  \texttt{"less"} para el caso \(<\) y \texttt{"greater"} para \(>\).
\item
  \texttt{p}: valor de referencia de la prueba.
\item
  \texttt{correct}: valor lógico para indicar si se usa la corrección de
  Yates.
\item
  \texttt{conf.level}: nivel de confianza para reportar el intervalo de
  confianza asociado (opcional).
\end{itemize}

Volvemos al ejemplo del quitamanchas

\[H_0: p = 0.90\] \[H_1: p < 0.90\]

La forma de usar la función \texttt{prop.test} para realizar la prueba
se muestra a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.test}\NormalTok{(}\AttributeTok{x=}\DecValTok{174}\NormalTok{, }\AttributeTok{n=}\DecValTok{200}\NormalTok{, }\AttributeTok{p=}\FloatTok{0.9}\NormalTok{, }\AttributeTok{alternative=}\StringTok{\textquotesingle{}less\textquotesingle{}}\NormalTok{,}
          \AttributeTok{conf.level=}\FloatTok{0.95}\NormalTok{, }\AttributeTok{correct=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  1-sample proportions test without continuity correction
## 
## data:  174 out of 200, null probability 0.9
## X-squared = 2, df = 1, p-value = 0.07865
## alternative hypothesis: true p is less than 0.9
## 95 percent confidence interval:
##  0.0000000 0.9042273
## sample estimates:
##    p 
## 0.87
\end{verbatim}

Como el valor-P (con valor de 0.07865 pero repotado en la salida como
0.08) es mayor que \(\alpha\) no se rechaza la hipótesis nula y se
concluye que no hay evidencias suficientes para rechazar la hipótesis
nula.

\hypertarget{prueba-binomial-exacta}{%
\subparagraph{Prueba binomial exacta}\label{prueba-binomial-exacta}}

Para realizar la prueba binomial exacta se usa la función
\texttt{binom.test} que tiene la siguiente estructura.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{binom.test}\NormalTok{(x, n, }\AttributeTok{p =} \FloatTok{0.5}\NormalTok{,}
           \AttributeTok{alternative =} \FunctionTok{c}\NormalTok{(}\StringTok{"two.sided"}\NormalTok{, }\StringTok{"less"}\NormalTok{, }\StringTok{"greater"}\NormalTok{),}
           \AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Los argumentos a definir dentro de \texttt{binom.test} para hacer la
prueba son:

\begin{itemize}
\tightlist
\item
  \texttt{x}: número de éxitos en la muestra.
\item
  \texttt{n}: número de observaciones en la muestra.
\item
  \texttt{alternative}: tipo de hipótesis alterna. Los valores
  disponibles son \texttt{"two.sided"} cuando la alterna es \(\neq\),
  \texttt{"less"} para el caso \(<\) y \texttt{"greater"} para \(>\).
\item
  \texttt{p}: valor de referencia de la prueba.
\item
  \texttt{conf.level}: nivel de confianza para reportar el intervalo de
  confianza asociado (opcional).
\end{itemize}

\hypertarget{otro-ejemplo}{%
\paragraph{Otro ejemplo}\label{otro-ejemplo}}

En una polleria asegura que 90\% de sus órdenes se entregan en menos de
10 minutos. En una muestra de 20 órdenes, 17 se entregaron dentro de ese
lapso. ¿Puede concluirse en el nivel de significancia 0.05, que menos de
90\% de las órdenes se entregan en menos de 10 minutos?

En este problema interesa probar lo siguiente:

\[H_0: p = 0.90\] \[H_1: p < 0.90\]

La forma de usar la función \texttt{binom.test} para realizar la prueba
se muestra a continuación.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{binom.test}\NormalTok{(}\AttributeTok{x=}\DecValTok{17}\NormalTok{, }\AttributeTok{n=}\DecValTok{20}\NormalTok{, }\AttributeTok{p=}\FloatTok{0.9}\NormalTok{, }\AttributeTok{alternative=}\StringTok{"less"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Exact binomial test
## 
## data:  17 and 20
## number of successes = 17, number of trials = 20, p-value = 0.3231
## alternative hypothesis: true probability of success is less than 0.9
## 95 percent confidence interval:
##  0.0000000 0.9578306
## sample estimates:
## probability of success 
##                   0.85
\end{verbatim}

Como el valor-P (reportado como 0.3 pero con valor de 0.3231) es mayor
que \(\alpha\) no se rechaza la hipótesis nula y se concluye que no hay
evidencias suficientes para rechazar la hipótesis nula.

\hypertarget{prueba-de-hipuxf3tesis-para-el-cociente-de-varianzas-sigma_12-sigma_22}{%
\subsubsection{\texorpdfstring{Prueba de hipótesis para el cociente de
varianzas
\(\sigma_1^2 / \sigma_2^2\)}{Prueba de hipótesis para el cociente de varianzas \textbackslash sigma\_1\^{}2 / \textbackslash sigma\_2\^{}2}}\label{prueba-de-hipuxf3tesis-para-el-cociente-de-varianzas-sigma_12-sigma_22}}

Para realizar este tipo de prueba se puede usar la función
\texttt{var.test}.

\hypertarget{ejemplo-tratamiento-porotos}{%
\paragraph{Ejemplo tratamiento
porotos}\label{ejemplo-tratamiento-porotos}}

Se realiza un estudio para comparar dos tratamientos que se aplicarán a
porotos crudos con el objetivo de reducir el tiempo de cocción. El
tratamiento T1 es a base de bicarbonato de sodio, el T2 es a base de
cloruro de sodio o sal común. La variable respuesta es el tiempo de
cocción en minutos. Los datos se muestran abajo. ¿Son las varianzas de
los tiempos iguales o diferentes? Usar \(\alpha=0.05\).

\textbf{T1}: 76, 85, 74, 78, 82, 75, 82.

\textbf{T2}: 57, 67, 55, 64, 61, 63, 63.

En este problema interesa probar si las varianzas poblacionales son
iguales o no, por esta razón el cociente de
\(\sigma_{T1}^2 / \sigma_{T2}^2\) se iguala al valor de 1 que será el
valor de referencia de la prueba.

\[H_0: \sigma_{T1}^2 / \sigma_{T2}^2 = 1\]
\[H_1: \sigma_{T1}^2 / \sigma_{T2}^2 \neq 1\]

Para ingresar los datos se hace lo siguiente:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{porotos }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\StringTok{"T1"}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\DecValTok{76}\NormalTok{, }\DecValTok{85}\NormalTok{, }\DecValTok{74}\NormalTok{,}\DecValTok{78}\NormalTok{, }\DecValTok{82}\NormalTok{, }\DecValTok{75}\NormalTok{, }\DecValTok{82}\NormalTok{), }\StringTok{"T2"}\OtherTok{=}\FunctionTok{c}\NormalTok{(}\DecValTok{57}\NormalTok{, }\DecValTok{67}\NormalTok{, }\DecValTok{55}\NormalTok{, }\DecValTok{64}\NormalTok{, }\DecValTok{61}\NormalTok{, }\DecValTok{63}\NormalTok{, }\DecValTok{63}\NormalTok{)))}

\FunctionTok{ggplot}\NormalTok{(porotos,}\FunctionTok{aes}\NormalTok{(}\AttributeTok{sample=}\NormalTok{T1)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_qq}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{geom\_qq\_line}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{\textquotesingle{}Cuantiles teóricos\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{\textquotesingle{}Cuantiles muestrales\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hiptest_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(porotos,}\FunctionTok{aes}\NormalTok{(}\AttributeTok{sample=}\NormalTok{T2)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_qq}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{geom\_qq\_line}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{\textquotesingle{}Cuantiles teóricos\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{ylab}\NormalTok{(}\StringTok{\textquotesingle{}Cuantiles muestrales\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hiptest_files/figure-latex/unnamed-chunk-10-2.pdf}

Una alternativa para probar normalidad: Tambien podemos plantear una
prueba de hipótesis la prueba de normalidad Kolmogorov-Smirnov

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{require}\NormalTok{(nortest) }
\FunctionTok{lillie.test}\NormalTok{(porotos}\SpecialCharTok{$}\NormalTok{T1)}\SpecialCharTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.520505
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{lillie.test}\NormalTok{(porotos}\SpecialCharTok{$}\NormalTok{T2)}\SpecialCharTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3952748
\end{verbatim}

Del QQplot mostrado en la Figura y las pruebas de normalidad se observa
que se puede asumir que las poblaciones son normales.

La función \texttt{var.test} se puede usar para probar \(H_0\), a
continuación el código para realizar la prueba.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var.test}\NormalTok{(porotos}\SpecialCharTok{$}\NormalTok{T1, porotos}\SpecialCharTok{$}\NormalTok{T2, }\AttributeTok{null.value=}\DecValTok{1}\NormalTok{, }\AttributeTok{alternative=}\StringTok{"two.sided"}\NormalTok{,}
         \AttributeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  porotos$T1 and porotos$T2
## F = 1.011, num df = 6, denom df = 6, p-value = 0.9897
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.1737219 5.8838861
## sample estimates:
## ratio of variances 
##           1.011019
\end{verbatim}

Como el valor-P es 0.9897 (reportado como 1 en la salida anterior), muy
superior al nivel \(\alpha\) de significancia 5\%, se puede concluir que
las varianzas son similares.

\hypertarget{ejemplo-as}{%
\paragraph{Ejemplo As}\label{ejemplo-as}}

El arsénico en agua potable es un posible riesgo para la salud. Un
artículo reciente reportó concentraciones de arsénico en agua potable en
partes por billón (ppb) para diez comunidades urbanas y diez comunidades
rurales. Los datos son los siguientes:

\textbf{Urbana}: 3, 7, 25, 10, 15, 6, 12, 25, 15, 7

\textbf{Rural}: 48, 44, 40, 38, 33, 21, 20, 12, 1, 18

¿Son las varianzas de las concentraciones iguales o diferentes? Usar
\(\alpha=0.05\).

En este problema interesa probar:

\[H_0: \sigma_{Urb}^2 / \sigma_{Rur}^2 = 1\]
\[H_1: \sigma_{Urb}^2 / \sigma_{Rur}^2 \neq 1\]

Para ingresar los datos se hace lo siguiente:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{As }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\StringTok{"urb"}\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{25}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{12}\NormalTok{, }\DecValTok{25}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{7}\NormalTok{) ,}
                         \StringTok{"rur"}\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{48}\NormalTok{, }\DecValTok{44}\NormalTok{, }\DecValTok{40}\NormalTok{, }\DecValTok{38}\NormalTok{, }\DecValTok{33}\NormalTok{, }\DecValTok{21}\NormalTok{, }\DecValTok{20}\NormalTok{, }\DecValTok{12}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{18}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

Primero se debe explorar si las muestras provienen de una población
normal

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{lillie.test}\NormalTok{(As}\SpecialCharTok{$}\NormalTok{urb)}\SpecialCharTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5522105
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{lillie.test}\NormalTok{(As}\SpecialCharTok{$}\NormalTok{rur)}\SpecialCharTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6249628
\end{verbatim}

La función \texttt{var.test} se puede usar para probar \(H_0\), a
continuación el código para realizar la prueba.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var.test}\NormalTok{(As}\SpecialCharTok{$}\NormalTok{urb, As}\SpecialCharTok{$}\NormalTok{rur, }\AttributeTok{null.value=}\DecValTok{1}\NormalTok{, }\AttributeTok{alternative=}\StringTok{"two.sided"}\NormalTok{,}
         \AttributeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  As$urb and As$rur
## F = 0.24735, num df = 9, denom df = 9, p-value = 0.04936
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.06143758 0.99581888
## sample estimates:
## ratio of variances 
##          0.2473473
\end{verbatim}

Como el valor-P es 0.0493604 (reportado como 0.05 en la salida anterior)
y es menor que el nivel de significancia \(\alpha=0.05\), se puede
concluir que las varianzas no son iguales.

\hypertarget{prueba-de-hipuxf3tesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-iguales}{%
\subsubsection{\texorpdfstring{Prueba de hipótesis para la diferencia de
medias \(\mu_1-\mu_2\) con varianzas
iguales}{Prueba de hipótesis para la diferencia de medias \textbackslash mu\_1-\textbackslash mu\_2 con varianzas iguales}}\label{prueba-de-hipuxf3tesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-iguales}}

Para realizar este tipo de prueba se puede usar la función
\texttt{t.test} que tiene la siguiente estructura.

\hypertarget{ejemplo-porotos}{%
\paragraph{Ejemplo porotos}\label{ejemplo-porotos}}

Retomando el ejemplo de los fríjoles, ¿existen diferencias entre los
tiempos de cocción de los fríjoles con T1 y T2? Usar un nivel de
significancia del 5\%.

Primero se construirá un boxplot comparativo para los tiempos de cocción
diferenciando por el tratamiento que recibieron.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{porotos }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols=}\FunctionTok{c}\NormalTok{(}\StringTok{"T1"}\NormalTok{,}\StringTok{"T2"}\NormalTok{), }\AttributeTok{names\_to =} \StringTok{"Trat"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{value, }\AttributeTok{fill=}\NormalTok{Trat)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{hiptest_files/figure-latex/porotos2-1.pdf}

Se muestra el boxplot, de esta figura se observa que las cajas de los
boxplot no se solapan, esto es un indicio de que las medias
poblacionales, \(\mu_1\) y \(\mu_2\), son diferentes, se observa también
que el boxplot para el tratamiento T1 está por encima del T2.

En este problema interesa estudiar el siguiente conjunto de hipótesis.

\[H_0: \mu_1  - \mu_2 = 0\] \[H_1: \mu_1  - \mu_2 \neq 0\]

El código para realizar la prueba es el siguiente:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(}\AttributeTok{x=}\NormalTok{porotos}\SpecialCharTok{$}\NormalTok{T1, }\AttributeTok{y=}\NormalTok{porotos}\SpecialCharTok{$}\NormalTok{T2, }\AttributeTok{alternative=}\StringTok{"two.sided"}\NormalTok{, }\AttributeTok{mu=}\DecValTok{0}\NormalTok{, }
       \AttributeTok{paired=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{var.equal=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{conf.level=}\FloatTok{0.97}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  porotos$T1 and porotos$T2
## t = 7.8209, df = 12, p-value = 4.737e-06
## alternative hypothesis: true difference in means is not equal to 0
## 97 percent confidence interval:
##  11.94503 22.91212
## sample estimates:
## mean of x mean of y 
##  78.85714  61.42857
\end{verbatim}

De la prueba se obtiene un valor-P muy pequeño, por lo tanto, podemos
concluir que si hay diferencias significativas entre los tiempos
promedios de cocción con T1 y T2, resultado que ya se sospechaba al
observar el boxplot

¿Cómo cocinamos los porotos?

\hypertarget{prueba-de-hipuxf3tesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-diferentes}{%
\subsubsection{\texorpdfstring{Prueba de hipótesis para la diferencia de
medias \(\mu_1-\mu_2\) con varianzas
diferentes}{Prueba de hipótesis para la diferencia de medias \textbackslash mu\_1-\textbackslash mu\_2 con varianzas diferentes}}\label{prueba-de-hipuxf3tesis-para-la-diferencia-de-medias-mu_1-mu_2-con-varianzas-diferentes}}

\hypertarget{ejemplo-as-1}{%
\paragraph{Ejemplo As}\label{ejemplo-as-1}}

Retomando el ejemplo de la concentración de arsénico en el agua,
¿existen diferencias entre las concentraciones de arsénico de la zona
urbana y rural? Usar un nivel de significancia del 5\%.

Primero hacemos un boxplot comparativo para las concentraciones de
arsénico diferenciando por la zona donde se tomaron las muestras.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{As }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols=}\FunctionTok{c}\NormalTok{(}\StringTok{"urb"}\NormalTok{,}\StringTok{"rur"}\NormalTok{), }\AttributeTok{names\_to =} \StringTok{"pobl"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{value, }\AttributeTok{fill=}\NormalTok{pobl)) }\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{hiptest_files/figure-latex/ars2-1.pdf}

n este problema interesa estudiar el siguiente conjunto de hipótesis.

\[H_0: \mu_1  - \mu_2 = 0\] \[H_1: \mu_1  - \mu_2 \neq 0\]

El código para realizar la prueba es el siguiente:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(}\AttributeTok{x=}\NormalTok{As}\SpecialCharTok{$}\NormalTok{urb, }\AttributeTok{y=}\NormalTok{As}\SpecialCharTok{$}\NormalTok{rur, }\AttributeTok{alternative=}\StringTok{"two.sided"}\NormalTok{, }\AttributeTok{mu=}\DecValTok{0}\NormalTok{, }
       \AttributeTok{paired=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{var.equal=}\ConstantTok{FALSE}\NormalTok{, }\AttributeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  As$urb and As$rur
## t = -2.7669, df = 13.196, p-value = 0.01583
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -26.694067  -3.305933
## sample estimates:
## mean of x mean of y 
##      12.5      27.5
\end{verbatim}

De la prueba se obtiene un valor-P pequeño, por lo tanto, podemos
concluir que si hay diferencias significativas entre las concentraciones
de arsénico del agua entre las dos zona. La zona que presenta mayor
concentración media de arsénico en el agua es la rural.

\end{document}
